In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [5]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [6]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [16]:
df.dropna(inplace=True)

In [17]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [18]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

In [19]:
df['Family_size'] = df['SibSp'] + df['Parch'] + 1

In [21]:
df.head()

    Age  Pclass  SibSp  Parch  Survived  Family_size
0  22.0       3      1      0         0            2
1  38.0       1      1      0         1            2
2  26.0       3      0      0         1            1
3  35.0       1      1      0         1            2
4  35.0       3      0      0         0            1

In [22]:
def myfunc(num):
    if num == 1:
        # Alone
        return 0
    elif num > 1 and num <= 4:
        # small family
        return 1
    else:
        # large family
        return 2

In [24]:
df['Family_type'] = df['Family_size'].apply(myfunc)

In [25]:
df.head()

    Age  Pclass  SibSp  Parch  Survived  Family_size  Family_type
0  22.0       3      1      0         0            2            1
1  38.0       1      1      0         1            2            1
2  26.0       3      0      0         1            1            0
3  35.0       1      1      0         1            2            1
4  35.0       3      0      0         0            1            0

In [27]:
X.drop(columns=['SibSp','Parch'],inplace=True)

In [28]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6961111111111111)