In [1]:
import numpy as np
import pandas as pd

In [5]:
date = pd.read_csv('D:\Programs\portfolio\MachineLearning\DataSets\orders.csv')
time = pd.read_csv('messages.csv')

In [6]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [7]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [9]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Working with Date

In [11]:
# Converting to datetime datatype because the datatype of date is object
date['date'] = pd.to_datetime(date['date'])

In [12]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

# Extracting Year

In [13]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
337 2019-07-15        4180       16       1       2019
455 2018-09-08        5330       26       6       2018
599 2019-06-05        2373       13      16       2019
75  2019-10-12         289       24       1       2019
662 2019-07-08        6290       23       1       2019

# Extracting Month

In [14]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

# Monht name

In [16]:
date['date_month_no'] = date['date'].dt.month_name()

date.head()

        date  product_id  city_id  orders  date_year date_month_no
0 2019-12-10        5628       25       3       2019      December
1 2018-08-15        3646       14     157       2018        August
2 2018-10-23        1859       25       1       2018       October
3 2019-08-17        7292       25       1       2019        August
4 2019-01-06        4344       25       3       2019       January

# Extract Days

In [17]:
date['date_day'] = date['date'].dt.day

date.head()

        date  product_id  city_id  orders  date_year date_month_no  date_day
0 2019-12-10        5628       25       3       2019      December        10
1 2018-08-15        3646       14     157       2018        August        15
2 2018-10-23        1859       25       1       2018       October        23
3 2019-08-17        7292       25       1       2019        August        17
4 2019-01-06        4344       25       3       2019       January         6

In [18]:
date['date_day'] = date['date'].dt.day_name()

date.head()

        date  product_id  city_id  orders  date_year date_month_no   date_day
0 2019-12-10        5628       25       3       2019      December    Tuesday
1 2018-08-15        3646       14     157       2018        August  Wednesday
2 2018-10-23        1859       25       1       2018       October    Tuesday
3 2019-08-17        7292       25       1       2019        August   Saturday
4 2019-01-06        4344       25       3       2019       January     Sunday

# Extract Day of weak

In [19]:
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow
0,2019-12-10,5628,25,3,2019,December,Tuesday,1
1,2018-08-15,3646,14,157,2018,August,Wednesday,2
2,2018-10-23,1859,25,1,2018,October,Tuesday,1
3,2019-08-17,7292,25,1,2019,August,Saturday,5
4,2019-01-06,4344,25,3,2019,January,Sunday,6

In [20]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year date_month_no   date_day  date_dow date_dow_name
0 2019-12-10       2019      December    Tuesday         1       Tuesday
1 2018-08-15       2018        August  Wednesday         2     Wednesday
2 2018-10-23       2018       October    Tuesday         1       Tuesday
3 2019-08-17       2019        August   Saturday         5      Saturday
4 2019-01-06       2019       January     Sunday         6        Sunday

In [21]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,Tuesday,1,Tuesday,0
1,2018-08-15,2018,August,Wednesday,2,Wednesday,0
2,2018-10-23,2018,October,Tuesday,1,Tuesday,0
3,2019-08-17,2019,August,Saturday,5,Saturday,1
4,2019-01-06,2019,January,Sunday,6,Sunday,1

# Extract Time elapsed between dates

In [22]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 27, 11, 26, 15, 691643)

In [24]:
today - date['date']

0     2421 days 11:26:15.691643
1     2903 days 11:26:15.691643
2     2834 days 11:26:15.691643
3     2536 days 11:26:15.691643
4     2759 days 11:26:15.691643
                 ...
995   2849 days 11:26:15.691643
996   2790 days 11:26:15.691643
997   2638 days 11:26:15.691643
998   2703 days 11:26:15.691643
999   2477 days 11:26:15.691643
Name: date, Length: 1000, dtype: timedelta64[ns]

In [27]:
(today - date['date']).dt.days

0      2421
1      2903
2      2834
3      2536
4      2759
       ...
995    2849
996    2790
997    2638
998    2703
999    2477
Name: date, Length: 1000, dtype: int64

In [29]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [30]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

# Extract Time

In [33]:
time['time'] = time['date'].dt.time

In [34]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

# Time difference

In [35]:
today - time['date']

0     4607 days 10:36:15.691643
1     4471 days 11:46:15.691643
2     4957 days 11:05:15.691643
3     4259 days 10:55:15.691643
4     4656 days 12:15:15.691643
                 ...
995   5246 days 10:36:15.691643
996   4567 days 12:12:15.691643
997   5032 days 11:49:15.691643
998   5148 days 11:52:15.691643
999   4420 days 12:01:15.691643
Name: date, Length: 1000, dtype: timedelta64[ns]

In [36]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.634716e+06
1      6.438946e+06
2      7.138745e+06
3      6.133615e+06
4      6.705375e+06
           ...
995    7.554876e+06
996    6.577212e+06
997    7.246789e+06
998    7.413832e+06
999    6.365521e+06
Name: date, Length: 1000, dtype: float64

In [37]:

# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      110578.604359
1      107315.771025
2      118979.087692
3      102226.921025
4      111756.254359
           ...
995    125914.604359
996    109620.204359
997    120779.821025
998    123563.871025
999    106092.021025
Name: date, Length: 1000, dtype: float64